import coursesCsv from '../project-assets/history_courses.csv?raw'
import classesCsv from '../project-assets/history_classes.csv?raw'
import instructorsCsv from '../project-assets/history_instructors.csv?raw'
import materialsCsv from '../project-assets/course_materials.csv?raw'

// Local media provided in project-assets. These are linked (built as URLs),
// never modified or generated by application code.
const materialUrls = import.meta.glob('../project-assets/materials/*', {
  eager: true,
  query: '?url',
  import: 'default',
})

const materialRaw = import.meta.glob('../project-assets/materials/*.md', {
  eager: true,
  query: '?raw',
  import: 'default',
})

function normalizeAssetKey(key) {
  return key.replace(/^\.\.\//, '')
}

export const materialUrlByPath = Object.fromEntries(
  Object.entries(materialUrls).map(([key, url]) => [normalizeAssetKey(key), url]),
)

export const materialRawByPath = Object.fromEntries(
  Object.entries(materialRaw).map(([key, raw]) => [normalizeAssetKey(key), raw]),
)

export function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i]

    if (inQuotes) {
      if (char === '"') {
        if (text[i + 1] === '"') {
          field += '"'
          i += 1
        } else {
          inQuotes = false
        }
      } else {
        field += char
      }
    } else if (char === '"') {
      inQuotes = true
    } else if (char === ',') {
      row.push(field)
      field = ''
    } else if (char === '\n') {
      row.push(field)
      field = ''
      rows.push(row)
      row = []
    } else if (char !== '\r') {
      field += char
    }
  }

  if (field.length > 0 || row.length > 0) {
    row.push(field)
    rows.push(row)
  }

  const [header, ...body] = rows
  if (!header) return []

  return body
    .filter((cells) => cells.some((cell) => cell.trim() !== ''))
    .map((cells) => {
      const record = {}
      header.forEach((key, index) => {
        record[key.trim()] = (cells[index] ?? '').trim()
      })
      return record
    })
}

export function toInt(value) {
  const parsed = Number.parseInt(value, 10)
  return Number.isNaN(parsed) ? 0 : parsed
}

export function resolveMaterial(record) {
  const path = record.file_path
  const assetPath = path.startsWith('project-assets/') ? path : `project-assets/${path}`
  return {
    id: record.material_id,
    courseId: record.course_id,
    classId: record.class_id,
    order: toInt(record.display_order),
    title: record.material_title,
    type: record.material_type,
    filePath: record.file_path,
    localUrl: materialUrlByPath[assetPath] ?? null,
    rawContent: materialRawByPath[assetPath] ?? null,
  }
}

const courseRecords = parseCsv(coursesCsv)
const classRecords = parseCsv(classesCsv)
const instructorRecords = parseCsv(instructorsCsv)
const materialRecords = parseCsv(materialsCsv)

export const instructors = Object.fromEntries(
  instructorRecords.map((record) => [
    record.instructor_id,
    {
      id: record.instructor_id,
      name: record.name,
      email: record.email,
      photoUrl: record.photo_url,
    },
  ]),
)

export const courses = courseRecords.map((record) => ({
  id: record.course_id,
  name: record.name,
  shortDescription: record.short_description,
  longDescription: record.long_description,
  numberOfClasses: toInt(record.number_of_classes),
  numberOfWeeks: toInt(record.number_of_weeks),
  instructorId: record.instructor_id,
  instructor: instructors[record.instructor_id] ?? null,
  imageUrl: record.image_url,
}))

export const classes = classRecords.map((record) => ({
  id: record.class_id,
  courseId: record.course_id,
  weekNumber: toInt(record.week_number),
  date: record.date,
  title: record.class_name,
}))

export const materials = materialRecords.map(resolveMaterial)

export function getMaterialsByClass(classId) {
  return materials
    .filter((material) => material.classId === classId)
    .sort((a, b) => a.order - b.order)
}

export function getClassesByCourse(courseId) {
  return classes
    .filter((classItem) => classItem.courseId === courseId)
    .sort((a, b) => {
      if (a.weekNumber !== b.weekNumber) return a.weekNumber - b.weekNumber
      return a.date.localeCompare(b.date)
    })
}

export function getCourseById(courseId) {
  return courses.find((course) => course.id === courseId) ?? null
}

export function formatDate(dateString) {
  if (!dateString) return ''
  const date = new Date(`${dateString}T12:00:00`)
  if (Number.isNaN(date.getTime())) return dateString
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  }).format(date)
}

export function getYouTubeEmbedUrl(url) {
  const match = url.match(/(?:youtu\.be\/|v=|embed\/|shorts\/)([A-Za-z0-9_-]{6,})/)
  return match ? `https://www.youtube-nocookie.com/embed/${match[1]}` : url
}
